/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SongsIndexRouteImport } from './routes/songs/index'
import { Route as SetlistsIndexRouteImport } from './routes/setlists/index'
import { Route as BooksIndexRouteImport } from './routes/books/index'
import { Route as SongsNewRouteImport } from './routes/songs/new'
import { Route as SongsSongIdRouteImport } from './routes/songs/$songId'
import { Route as SetlistsNewRouteImport } from './routes/setlists/new'
import { Route as SetlistsSetlistIdRouteImport } from './routes/setlists/$setlistId'
import { Route as BooksNewRouteImport } from './routes/books/new'
import { Route as BooksBookIdRouteImport } from './routes/books/$bookId'
import { Route as SongsSongIdEditRouteImport } from './routes/songs/$songId.edit'
import { Route as SetlistsSetlistIdEditRouteImport } from './routes/setlists/$setlistId.edit'
import { Route as BooksBookIdEditRouteImport } from './routes/books/$bookId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SongsIndexRoute = SongsIndexRouteImport.update({
  id: '/songs/',
  path: '/songs/',
  getParentRoute: () => rootRouteImport,
} as any)
const SetlistsIndexRoute = SetlistsIndexRouteImport.update({
  id: '/setlists/',
  path: '/setlists/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksIndexRoute = BooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => rootRouteImport,
} as any)
const SongsNewRoute = SongsNewRouteImport.update({
  id: '/songs/new',
  path: '/songs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SongsSongIdRoute = SongsSongIdRouteImport.update({
  id: '/songs/$songId',
  path: '/songs/$songId',
  getParentRoute: () => rootRouteImport,
} as any)
const SetlistsNewRoute = SetlistsNewRouteImport.update({
  id: '/setlists/new',
  path: '/setlists/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SetlistsSetlistIdRoute = SetlistsSetlistIdRouteImport.update({
  id: '/setlists/$setlistId',
  path: '/setlists/$setlistId',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksNewRoute = BooksNewRouteImport.update({
  id: '/books/new',
  path: '/books/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksBookIdRoute = BooksBookIdRouteImport.update({
  id: '/books/$bookId',
  path: '/books/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const SongsSongIdEditRoute = SongsSongIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => SongsSongIdRoute,
} as any)
const SetlistsSetlistIdEditRoute = SetlistsSetlistIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => SetlistsSetlistIdRoute,
} as any)
const BooksBookIdEditRoute = BooksBookIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => BooksBookIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/books/$bookId': typeof BooksBookIdRouteWithChildren
  '/books/new': typeof BooksNewRoute
  '/setlists/$setlistId': typeof SetlistsSetlistIdRouteWithChildren
  '/setlists/new': typeof SetlistsNewRoute
  '/songs/$songId': typeof SongsSongIdRouteWithChildren
  '/songs/new': typeof SongsNewRoute
  '/books/': typeof BooksIndexRoute
  '/setlists/': typeof SetlistsIndexRoute
  '/songs/': typeof SongsIndexRoute
  '/books/$bookId/edit': typeof BooksBookIdEditRoute
  '/setlists/$setlistId/edit': typeof SetlistsSetlistIdEditRoute
  '/songs/$songId/edit': typeof SongsSongIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/books/$bookId': typeof BooksBookIdRouteWithChildren
  '/books/new': typeof BooksNewRoute
  '/setlists/$setlistId': typeof SetlistsSetlistIdRouteWithChildren
  '/setlists/new': typeof SetlistsNewRoute
  '/songs/$songId': typeof SongsSongIdRouteWithChildren
  '/songs/new': typeof SongsNewRoute
  '/books': typeof BooksIndexRoute
  '/setlists': typeof SetlistsIndexRoute
  '/songs': typeof SongsIndexRoute
  '/books/$bookId/edit': typeof BooksBookIdEditRoute
  '/setlists/$setlistId/edit': typeof SetlistsSetlistIdEditRoute
  '/songs/$songId/edit': typeof SongsSongIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/books/$bookId': typeof BooksBookIdRouteWithChildren
  '/books/new': typeof BooksNewRoute
  '/setlists/$setlistId': typeof SetlistsSetlistIdRouteWithChildren
  '/setlists/new': typeof SetlistsNewRoute
  '/songs/$songId': typeof SongsSongIdRouteWithChildren
  '/songs/new': typeof SongsNewRoute
  '/books/': typeof BooksIndexRoute
  '/setlists/': typeof SetlistsIndexRoute
  '/songs/': typeof SongsIndexRoute
  '/books/$bookId/edit': typeof BooksBookIdEditRoute
  '/setlists/$setlistId/edit': typeof SetlistsSetlistIdEditRoute
  '/songs/$songId/edit': typeof SongsSongIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/books/$bookId'
    | '/books/new'
    | '/setlists/$setlistId'
    | '/setlists/new'
    | '/songs/$songId'
    | '/songs/new'
    | '/books/'
    | '/setlists/'
    | '/songs/'
    | '/books/$bookId/edit'
    | '/setlists/$setlistId/edit'
    | '/songs/$songId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/books/$bookId'
    | '/books/new'
    | '/setlists/$setlistId'
    | '/setlists/new'
    | '/songs/$songId'
    | '/songs/new'
    | '/books'
    | '/setlists'
    | '/songs'
    | '/books/$bookId/edit'
    | '/setlists/$setlistId/edit'
    | '/songs/$songId/edit'
  id:
    | '__root__'
    | '/'
    | '/books/$bookId'
    | '/books/new'
    | '/setlists/$setlistId'
    | '/setlists/new'
    | '/songs/$songId'
    | '/songs/new'
    | '/books/'
    | '/setlists/'
    | '/songs/'
    | '/books/$bookId/edit'
    | '/setlists/$setlistId/edit'
    | '/songs/$songId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BooksBookIdRoute: typeof BooksBookIdRouteWithChildren
  BooksNewRoute: typeof BooksNewRoute
  SetlistsSetlistIdRoute: typeof SetlistsSetlistIdRouteWithChildren
  SetlistsNewRoute: typeof SetlistsNewRoute
  SongsSongIdRoute: typeof SongsSongIdRouteWithChildren
  SongsNewRoute: typeof SongsNewRoute
  BooksIndexRoute: typeof BooksIndexRoute
  SetlistsIndexRoute: typeof SetlistsIndexRoute
  SongsIndexRoute: typeof SongsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/songs/': {
      id: '/songs/'
      path: '/songs'
      fullPath: '/songs/'
      preLoaderRoute: typeof SongsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setlists/': {
      id: '/setlists/'
      path: '/setlists'
      fullPath: '/setlists/'
      preLoaderRoute: typeof SetlistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/': {
      id: '/books/'
      path: '/books'
      fullPath: '/books/'
      preLoaderRoute: typeof BooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/songs/new': {
      id: '/songs/new'
      path: '/songs/new'
      fullPath: '/songs/new'
      preLoaderRoute: typeof SongsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/songs/$songId': {
      id: '/songs/$songId'
      path: '/songs/$songId'
      fullPath: '/songs/$songId'
      preLoaderRoute: typeof SongsSongIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setlists/new': {
      id: '/setlists/new'
      path: '/setlists/new'
      fullPath: '/setlists/new'
      preLoaderRoute: typeof SetlistsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setlists/$setlistId': {
      id: '/setlists/$setlistId'
      path: '/setlists/$setlistId'
      fullPath: '/setlists/$setlistId'
      preLoaderRoute: typeof SetlistsSetlistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/new': {
      id: '/books/new'
      path: '/books/new'
      fullPath: '/books/new'
      preLoaderRoute: typeof BooksNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$bookId': {
      id: '/books/$bookId'
      path: '/books/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof BooksBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/songs/$songId/edit': {
      id: '/songs/$songId/edit'
      path: '/edit'
      fullPath: '/songs/$songId/edit'
      preLoaderRoute: typeof SongsSongIdEditRouteImport
      parentRoute: typeof SongsSongIdRoute
    }
    '/setlists/$setlistId/edit': {
      id: '/setlists/$setlistId/edit'
      path: '/edit'
      fullPath: '/setlists/$setlistId/edit'
      preLoaderRoute: typeof SetlistsSetlistIdEditRouteImport
      parentRoute: typeof SetlistsSetlistIdRoute
    }
    '/books/$bookId/edit': {
      id: '/books/$bookId/edit'
      path: '/edit'
      fullPath: '/books/$bookId/edit'
      preLoaderRoute: typeof BooksBookIdEditRouteImport
      parentRoute: typeof BooksBookIdRoute
    }
  }
}

interface BooksBookIdRouteChildren {
  BooksBookIdEditRoute: typeof BooksBookIdEditRoute
}

const BooksBookIdRouteChildren: BooksBookIdRouteChildren = {
  BooksBookIdEditRoute: BooksBookIdEditRoute,
}

const BooksBookIdRouteWithChildren = BooksBookIdRoute._addFileChildren(
  BooksBookIdRouteChildren,
)

interface SetlistsSetlistIdRouteChildren {
  SetlistsSetlistIdEditRoute: typeof SetlistsSetlistIdEditRoute
}

const SetlistsSetlistIdRouteChildren: SetlistsSetlistIdRouteChildren = {
  SetlistsSetlistIdEditRoute: SetlistsSetlistIdEditRoute,
}

const SetlistsSetlistIdRouteWithChildren =
  SetlistsSetlistIdRoute._addFileChildren(SetlistsSetlistIdRouteChildren)

interface SongsSongIdRouteChildren {
  SongsSongIdEditRoute: typeof SongsSongIdEditRoute
}

const SongsSongIdRouteChildren: SongsSongIdRouteChildren = {
  SongsSongIdEditRoute: SongsSongIdEditRoute,
}

const SongsSongIdRouteWithChildren = SongsSongIdRoute._addFileChildren(
  SongsSongIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BooksBookIdRoute: BooksBookIdRouteWithChildren,
  BooksNewRoute: BooksNewRoute,
  SetlistsSetlistIdRoute: SetlistsSetlistIdRouteWithChildren,
  SetlistsNewRoute: SetlistsNewRoute,
  SongsSongIdRoute: SongsSongIdRouteWithChildren,
  SongsNewRoute: SongsNewRoute,
  BooksIndexRoute: BooksIndexRoute,
  SetlistsIndexRoute: SetlistsIndexRoute,
  SongsIndexRoute: SongsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
